name: pytorch1.12
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - pyg
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2026.1.4
  - certifi=2024.8.30
  - cudatoolkit=11.6.0
  - et_xmlfile=1.1.0
  - fftw=3.3.9
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - networkx=2.6.3
  - numexpr=2.7.3
  - numpy-base=1.21.5
  - openpyxl=3.0.9
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=1.3.5
  - pip=22.3.1
  - pyparsing=3.0.9
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - scikit-learn=1.0.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.45.3
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tqdm=4.64.1
  - wheel=0.38.4
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - args==0.1.0
    - attrs==24.2.0
    - cachetools==5.5.0
    - charset-normalizer==3.4.0
    - click==8.1.8
    - click-plugins==1.1.1.2
    - cligj==0.7.2
    - clint==0.5.1
    - clip==1.0
    - coverage==7.2.7
    - cycler==0.11.0
    - cython==3.0.12
    - einops==0.6.1
    - fiona==1.9.6
    - fonttools==4.38.0
    - ftfy==6.1.1
    - geographiclib==2.1
    - geopandas==0.10.2
    - geopy==2.4.1
    - google-auth==2.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.62.3
    - h3==3.7.7
    - idna==3.10
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - jinja2==3.1.6
    - kiwisolver==1.4.5
    - mamba==0.11.3
    - markdown==3.4.4
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - nltk==3.8.1
    - nose==1.3.7
    - nuitka==2.8.9
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opencv-python==4.12.0.88
    - ordered-set==4.1.0
    - osmnx==1.1.2
    - pillow==9.5.0
    - protobuf==3.20.3
    - psutil==7.2.1
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pykalman==0.9.7
    - pyproj==3.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - recsys-metrics==0.0.4
    - regex==2024.4.16
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - rtree==1.0.1
    - scikit-image==0.19.3
    - scipy==1.6.0
    - shapely==1.8.5.post1
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorly==0.4.4
    - tifffile==2021.11.2
    - timezonefinder==6.0.1
    - torch==1.12.1+cu116
    - torch-geometric==2.3.1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.14
    - torch-tb-profiler==0.4.1
    - torchaudio==0.12.1+cu116
    - torchvision==0.13.1+cu116
    - transbigdata==0.5.3
    - typing-extensions==4.7.1
    - urllib3==2.0.7
    - wcwidth==0.2.13
    - werkzeug==2.2.3
    - zipp==3.15.0
    - zstandard==0.21.0
